# This is a basic workflow to help you get started with Actions

name: Deploy to Github Pages

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            # Any prerequisite steps
            - uses: actions/checkout@master

            # Build
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            - name: npm install and build
              run: |
                  npm install
                  npm run build
            # Deploy to local repo
            - name: Auto build into Production
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: production # The branch the action should deploy to.
                  folder: dist # The folder the action should deploy.
